name: Deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4
    - name: Setup Ruby 💎
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4.2"
        bundler-cache: true
    - name: Install and Build 🔧
    run: |
      sudo apt-get update && sudo apt-get install -y imagemagick
      pip3 install --upgrade nbconvert
      export JEKYLL_ENV=production
      bundle exec jekyll build
    - name: Deploy
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site
